# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-23 12:58
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('index', models.PositiveSmallIntegerField()),
                ('assessment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('desc', models.TextField(blank=True, null=True)),
                ('beginDate', models.DateField(blank=True, null=True)),
                ('duration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('avgRating', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dob', models.DateField()),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('desc', models.TextField()),
                ('avgRating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialAnswers', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('permissions', models.ManyToManyField(blank=True, to='elearning.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('desc', models.TextField(blank=True, null=True)),
                ('beginDate', models.DateField(blank=True, null=True)),
                ('index', models.PositiveSmallIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='HTMLBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='elearning.Block')),
                ('content', models.TextField()),
            ],
            bases=('elearning.block',),
        ),
        migrations.CreateModel(
            name='ImageBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='elearning.Block')),
                ('subtitle', models.CharField(blank=True, max_length=40, null=True)),
                ('image', models.ImageField(upload_to='')),
            ],
            bases=('elearning.block',),
        ),
        migrations.CreateModel(
            name='QuizBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='elearning.Block')),
                ('serialQuestions', models.TextField()),
            ],
            bases=('elearning.block',),
        ),
        migrations.CreateModel(
            name='VideoBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='elearning.Block')),
                ('url', models.URLField(max_length=250)),
            ],
            bases=('elearning.block',),
        ),
        migrations.AddField(
            model_name='progress',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.Block'),
        ),
        migrations.AddField(
            model_name='progress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.CustomUser'),
        ),
        migrations.AddField(
            model_name='programme',
            name='tags',
            field=models.ManyToManyField(blank=True, to='elearning.Tag'),
        ),
        migrations.AddField(
            model_name='programme',
            name='users',
            field=models.ManyToManyField(blank=True, to='elearning.CustomUser'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elearning.Role'),
        ),
        migrations.AddField(
            model_name='course',
            name='programmes',
            field=models.ManyToManyField(blank=True, to='elearning.Programme'),
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, to='elearning.Tag'),
        ),
        migrations.AddField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(blank=True, to='elearning.CustomUser'),
        ),
        migrations.AddField(
            model_name='block',
            name='sections',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.Section'),
        ),
    ]
