# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0003_auto_20160408_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='elearning.Block')),
                ('image', models.ImageField(upload_to=b'')),
                ('docfile', models.FileField(upload_to='files/%Y/%m/%d')),
            ],
            bases=('elearning.block',),
        ),
    ]
