# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 20:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0004_imageblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageblock',
            name='docfile',
        ),
        migrations.AddField(
            model_name='imageblock',
            name='title',
            field=models.CharField(default=datetime.datetime(2016, 4, 13, 20, 18, 59, 368964, tzinfo=utc), max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imageblock',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
