# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0005_auto_20160413_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
