# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0007_auto_20160413_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='sections',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elearning.Section'),
        ),
    ]
