# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0010_auto_20160415_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
