# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 14:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0011_auto_20160415_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoblock',
            name='url',
            field=models.URLField(default=datetime.datetime(2016, 4, 16, 14, 16, 4, 609456, tzinfo=utc), max_length=250),
            preserve_default=False,
        ),
    ]
