# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0014_auto_20160417_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageblock',
            name='title',
        ),
        migrations.AddField(
            model_name='course',
            name='avgRating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='imageblock',
            name='subtitle',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='assessment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='block',
            name='index',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='block',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='block',
            name='sections',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.Section'),
        ),
        migrations.AlterField(
            model_name='course',
            name='programmes',
            field=models.ManyToManyField(blank=True, to='elearning.Programme'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, to='elearning.Tag'),
        ),
        migrations.AlterField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(blank=True, to='elearning.CustomUser'),
        ),
        migrations.AlterField(
            model_name='imageblock',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='programme',
            name='avgRating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='tags',
            field=models.ManyToManyField(blank=True, to='elearning.Tag'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='users',
            field=models.ManyToManyField(blank=True, to='elearning.CustomUser'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='elearning.Permission'),
        ),
        migrations.AlterField(
            model_name='section',
            name='beginDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
